source.. = src/,\
           test/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               images/,\
               plugin_ja.properties,\
               plugin.properties,\
               lib/,\
               schema/,\
               lib/poi-5.5.1.jar,\
               lib/poi-ooxml-5.5.1.jar,\
               resources/,\
               template/

